/**
 * poe.ninja JSON API client (main-process only, no DOM).
 *
 * poe.ninja's public API is undocumented and was mapped empirically (see
 * docs/api-endpoints.md, generated by scripts/discover-api.js) rather than from any spec.
 * It has already been observed to differ between games for the *same* category — POE2 uses
 * plural `type` values (`UniqueWeapons`) while POE1 uses singular (`UniqueWeapon`) on the same
 * endpoint family. Treat the endpoint family and type-name casing as UNSTABLE: resolve them
 * adaptively at runtime by trying candidates and caching whichever one responds with 200, rather
 * than hardcoding a fixed map. If poe.ninja changes shape again, re-run discover-api.js.
 */

const { net } = require('electron');

const BASE = 'https://poe.ninja';
const REQUEST_TIMEOUT_MS = 10_000;
const MAX_RETRIES = 2;

// endpoint family templates, tried in this order until one resolves (200)
const FAMILIES = [
  (game, league, type) =>
    `${BASE}/${game}/api/economy/stash/current/item/overview?league=${encodeURIComponent(league)}&type=${type}`,
  (game, league, type) =>
    `${BASE}/${game}/api/economy/exchange/current/overview?league=${encodeURIComponent(league)}&type=${type}`,
];

// resolved (family index, type variant) per "game:category", so we don't re-probe every call
const resolvedCombo = new Map();

function pascalWords(slug) {
  return slug.split('-').filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1));
}

/** Two plausible `type` query values for a category slug — plural and last-word-singular. */
function typeVariants(categorySlug) {
  const words = pascalWords(categorySlug);
  const plural = words.join('');
  const last = words[words.length - 1];
  const singularLast = last.endsWith('s') ? last.slice(0, -1) : last;
  const singular = [...words.slice(0, -1), singularLast].join('');
  return [...new Set([plural, singular])];
}

function httpGetJson(url) {
  return new Promise((resolve, reject) => {
    const request = net.request({ method: 'GET', url });
    request.setHeader('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:152.0) Gecko/20100101 Firefox/152.0');

    const timer = setTimeout(() => {
      request.abort();
      reject(new Error(`timeout after ${REQUEST_TIMEOUT_MS}ms: ${url}`));
    }, REQUEST_TIMEOUT_MS);

    request.on('response', (response) => {
      let raw = '';
      response.on('data', (chunk) => (raw += chunk));
      response.on('end', () => {
        clearTimeout(timer);
        if (response.statusCode !== 200) {
          resolve({ status: response.statusCode, json: null });
          return;
        }
        try {
          resolve({ status: 200, json: JSON.parse(raw) });
        } catch (e) {
          reject(new Error(`invalid JSON from ${url}: ${e.message}`));
        }
      });
      response.on('error', (e) => {
        clearTimeout(timer);
        reject(e);
      });
    });
    request.on('error', (e) => {
      clearTimeout(timer);
      reject(e);
    });
    request.end();
  });
}

async function getWithRetry(url) {
  let lastErr;
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      return await httpGetJson(url);
    } catch (e) {
      lastErr = e;
      if (attempt < MAX_RETRIES) await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
    }
  }
  throw lastErr;
}

/** League list for a game: [{ slug, displayName, hardcore, indexed }]. */
async function getLeagues(game) {
  const { status, json } = await getWithRetry(`${BASE}/${game}/api/data/index-state`);
  if (status !== 200 || !json || !Array.isArray(json.economyLeagues)) return [];
  return json.economyLeagues.map((l) => ({
    slug: l.url,
    displayName: l.displayName || l.name,
    hardcore: !!l.hardcore,
    indexed: !!l.indexed,
  }));
}

// Value field convention differs by game+endpoint: POE2 (both endpoint families) and POE1's
// exchange family use unified `primaryValue` + a `core.primary` currency name. POE1's stash/item
// family predates that unification and instead has explicit `chaosValue`/`exaltedValue`/`divineValue`
// fields with no `core` object at all. Try each in turn rather than assuming one schema.
// Returns { amount, unit } (both null if no numeric value is present at all) instead of a
// pre-formatted string, so callers can both display it and do currency conversion/ranking.
function extractValue(row, corePrimary) {
  if (typeof row.primaryValue === 'number' && corePrimary) return { amount: row.primaryValue, unit: corePrimary };
  if (typeof row.divineValue === 'number') return { amount: row.divineValue, unit: 'Divine' };
  if (typeof row.exaltedValue === 'number') return { amount: row.exaltedValue, unit: 'Exalted' };
  if (typeof row.chaosValue === 'number') return { amount: row.chaosValue, unit: 'Chaos' };
  return { amount: null, unit: '' };
}

function normalizeRow(row, itemsById, corePrimary) {
  const meta = itemsById ? itemsById.get(row.id) : null;
  const name = row.name || (meta && meta.name) || String(row.id);
  const icon = row.icon || (meta && meta.image ? `https://web.poecdn.com${meta.image}` : '');
  const { amount, unit } = extractValue(row, corePrimary);
  const value = amount !== null ? `${amount} ${unit}` : '';
  const sparkline = row.sparkline || row.sparkLine || null;
  const totalChange = sparkline && typeof sparkline.totalChange === 'number' ? sparkline.totalChange : null;
  const changePercent = totalChange !== null ? `${totalChange > 0 ? '+' : ''}${totalChange}%` : '';
  const trend = sparkline && Array.isArray(sparkline.data) ? sparkline.data : null;
  return { name, value, changePercent, icon, amount, unit, trend };
}

function capitalize(s) {
  return s ? s[0].toUpperCase() + s.slice(1) : s;
}

/**
 * Core adaptive resolution shared by every endpoint lookup in this file: try candidate
 * (endpoint family, type-name) combos for a category until one produces a response
 * `isAcceptable` deems useful, caching the winning combo per game+category. This is the ONLY
 * place that resolves family/type — callers must not hardcode a family index or type literal
 * (see the file header: poe.ninja's endpoint shape is unstable and must be probed, not assumed).
 *
 * Returns the raw JSON body, or the first "empty but valid" body if nothing was acceptable
 * (callers decide what an empty result means for them), or null if every candidate failed
 * outright (network error / no matching endpoint at all).
 */
async function resolveCategoryJson(game, league, categorySlug, isAcceptable) {
  const cacheKey = `${game}:${categorySlug}`;
  const candidates = [];

  if (resolvedCombo.has(cacheKey)) {
    candidates.push(resolvedCombo.get(cacheKey));
  } else {
    for (let familyIdx = 0; familyIdx < FAMILIES.length; familyIdx++) {
      for (const type of typeVariants(categorySlug)) {
        candidates.push({ familyIdx, type });
      }
    }
  }

  // A 200 with an "inconclusive" body is valid — some endpoint families answer every type with
  // 200/empty rather than 404. Only lock in a resolution once a candidate is actually acceptable;
  // otherwise keep trying, and fall back to the first inconclusive body seen (a genuinely empty
  // category) without caching it as "the" combo.
  let fallbackJson = null;

  for (const { familyIdx, type } of candidates) {
    const url = FAMILIES[familyIdx](game, league, type);
    let result;
    try {
      result = await getWithRetry(url);
    } catch (e) {
      console.error(`resolveCategoryJson ${game}/${categorySlug} (${url}):`, e.message);
      continue;
    }
    if (result.status !== 200 || !result.json) continue;

    if (!isAcceptable(result.json)) {
      if (!fallbackJson) fallbackJson = result.json;
      continue;
    }

    resolvedCombo.set(cacheKey, { familyIdx, type });
    return result.json;
  }

  return fallbackJson; // no candidate was acceptable — category empty or unavailable right now
}

/**
 * Fetch one category for a game+league. Returns normalized rows, or [] if poe.ninja has no
 * data / no matching endpoint for this category right now — never throws for a single bad
 * category so one broken slug can't take down a whole background refresh.
 *
 * `league` must be the league's display name (e.g. "Runes of Aldur"), NOT its URL slug
 * ("runesofaldur") — the query param silently returns an empty-but-valid 200 for the slug.
 * Use the `displayName` field from getLeagues().
 */
async function fetchCategory(game, league, categorySlug) {
  const json = await resolveCategoryJson(game, league, categorySlug, (j) => Array.isArray(j.lines) && j.lines.length > 0);
  if (!json) return [];

  const lines = Array.isArray(json.lines) ? json.lines : [];
  const itemsById = Array.isArray(json.items) ? new Map(json.items.map((it) => [it.id, it])) : null;
  const corePrimary = json.core && json.core.primary ? capitalize(json.core.primary) : '';
  return lines.map((row) => normalizeRow(row, itemsById, corePrimary));
}

/**
 * Currency conversion table for a game+league: { primary, rates }, where `rates[unit]` is
 * "how many of `unit` equal 1 `primary`" (e.g. primary="divine", rates={chaos: 8.04} means
 * 1 divine = 8.04 chaos). Sourced from the `core` block of the currency exchange overview,
 * which every league that has any economy data at all exposes. Used to compare item values
 * that were reported in different currencies (see extractValue's per-schema fallback above).
 *
 * Resolved via the same adaptive mechanism as fetchCategory (categorySlug 'currency' shares its
 * resolvedCombo cache entry with fetchCategory(..., 'currency') — both need the same endpoint).
 */
async function getExchangeRates(game, league) {
  const json = await resolveCategoryJson(game, league, 'currency', (j) => !!(j.core && j.core.primary));
  if (json && json.core && json.core.primary) {
    return { primary: capitalize(json.core.primary), rates: json.core.rates || {} };
  }
  return { primary: 'Chaos', rates: {} }; // no data for this league — caller should treat as unknown
}

module.exports = { getLeagues, fetchCategory, getExchangeRates, typeVariants };
